#include "block_cipher_mode.hh"
#include "cipher.h"
#include <gtest/gtest.h>
#include <map>
#include <string>

#define CREATE_ECB_TEST(alg, size) BlockCipherTestParams(CIPHER_MODE_ECB, alg, size)

class ECBTests : public BlockCipherModeTests {
protected:
	block_cipher_func *get_block_cipher_func_cipher() const final {
		return ECB_encrypt;
	}

	block_cipher_func *get_block_cipher_func_decipher() const final {
		return ECB_decrypt;
	}

public:
	~ECBTests() override = default;
};

static const std::vector<BlockCipherTestParams> ecb_aes128_params{
	CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 0),   CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 1),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 8),   CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 16),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 26),  CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 31),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 32),  CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 73),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 79),  CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 128),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES128, 512),
};

static const std::vector<BlockCipherTestParams> ecb_aes192_params{
	CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 0),   CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 1),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 8),   CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 16),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 26),  CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 31),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 32),  CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 73),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 79),  CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 128),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES192, 512),
};

static const std::vector<BlockCipherTestParams> ecb_aes256_params{
	CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 0),   CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 1),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 8),   CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 16),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 26),  CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 31),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 32),  CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 73),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 79),  CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 128),
	CREATE_ECB_TEST(BLOCK_CIPHER_AES256, 512),
};

static const std::vector<BlockCipherTestParams> ecb_des_params{
	CREATE_ECB_TEST(BLOCK_CIPHER_DES, 0),   CREATE_ECB_TEST(BLOCK_CIPHER_DES, 1),
	CREATE_ECB_TEST(BLOCK_CIPHER_DES, 8),   CREATE_ECB_TEST(BLOCK_CIPHER_DES, 16),
	CREATE_ECB_TEST(BLOCK_CIPHER_DES, 26),  CREATE_ECB_TEST(BLOCK_CIPHER_DES, 31),
	CREATE_ECB_TEST(BLOCK_CIPHER_DES, 32),  CREATE_ECB_TEST(BLOCK_CIPHER_DES, 73),
	CREATE_ECB_TEST(BLOCK_CIPHER_DES, 79),  CREATE_ECB_TEST(BLOCK_CIPHER_DES, 128),
	CREATE_ECB_TEST(BLOCK_CIPHER_DES, 512),
};

INSTANTIATE_TEST_SUITE_P(aes128, ECBTests, testing::ValuesIn(ecb_aes128_params));
INSTANTIATE_TEST_SUITE_P(aes192, ECBTests, testing::ValuesIn(ecb_aes192_params));
INSTANTIATE_TEST_SUITE_P(aes256, ECBTests, testing::ValuesIn(ecb_aes256_params));
INSTANTIATE_TEST_SUITE_P(des, ECBTests, testing::ValuesIn(ecb_des_params));

TEST_P(ECBTests, cipher) {
	run_cipher_test();
}

TEST_P(ECBTests, decipher) {
	run_decipher_test();
}