name: Run tests on libcrypto42

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Get CUnit
      run: sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev
      
    - name: Compile libft
      run: make -C libft

    - name: make
      run: make
    - name: make check
      run: make check
