name: Tests_libcrypto42

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get CUnit
      run: sudo apt-get install -y libcriterion-dev

    - name: Compile libft
      run: make -C libft

    - name: make
      run: make
    - name: make check
      run: make check
  
  
    - name: Badge Action
      uses: emibcn/badge-action@v1.2.4
      with:
        label: Testing libcrypto42
