name: 'Unit tests'

on:
  push:
    paths:
      - ".github/workflows/tests.yml"
      - "./src/**.c"
      - "./include/**.h"
      - "./tests/**.c"
      - "**.test.c"
      - Makefile
      - "mkvars/**.mk"
  pull_request:
    paths:
      - ".github/workflows/tests.yml"
      - "./src/**.c"
      - "./include/**.h"
      - "./tests/**.c"
      - "**.test.c"
      - Makefile
      - "mkvars/**.mk"

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Installing criterion
        run: sudo apt-get install -y libcriterion-dev

      - name: Compile libft
        run: make -C libft
      - name: Compile libcrypto42
        run: make
      - name: Running tests
        run: make check